// build.gradle
plugins {
    id 'application' // Adds Java support and application execution capabilities
}

repositories {
    mavenCentral() // Tells Gradle where to look for dependencies if needed
}

application {
    mainClass = 'com.example.Main' // Points Gradle to your main method
}

dependencies {
    implementation 'com.google.inject:guice:7.0.0'
    implementation 'org.postgresql:postgresql:42.7.4'
}
